### PR TITLE
Dockerize App

### PR DESCRIPTION
**Pull request by InterXellar**
Hi,

I have dockerized the app, nothing big.
Only Dockerfile & .dockerignore have been added, the Docker container/image was built successfully and tested on a Linux host. 

If needed a docker-compose.yml can be supplied too.

### CODE REVIEW

**Comment by rmcproductions** [comment]
Hello and thank you for providing this pull request. I will have to review it tomorrow because reviewing PRs on mobile is kinda not the coolest thing.

**Comment by rmcproductions** [comment]
Hello, from what I can see, there's no way to edit the config file which means the container will always run on the default config. Is that intended? I would like the container to be filled with the config file to be able for admins to change cooldowns etc.

**Comment by byNoobiYT** [comment]
You can copy files from your host to your container using `docker cp`.

**Comment by rmcproductions** [comment]
> You can copy files from your host to your container using `docker cp`.

Yes, but is this change persistent? I'm talking about an integration like @InterXellar has done it for the `package*.json`, so the changes a user may have made to the config are still there even after deleting/rebuilding the container.

**Comment by byNoobiYT** [comment]
Files will be persistent as long as you do not delete the container.

**Comment by rmcproductions** [comment]
Which is why I'd want that to be integrated into the docker file. E.g. a simple `COPY config.json ./` would do the trick - so the file will also be updated on a rebuild of the container.
However if that was not intended to be like that by @InterXellar, I'd merge this as is.

**Comment by Erik1000** [comment]
This is not how docker should be used. 
The better way would be to change the location where your code searches for the config file and then mount a file from the host to the container. In this case your config will be available as long as you mount the volume.
You should do this for nearly anything except executables (your actual code).

**Comment by InterXellar** [comment]
A persistent config will be provided with the docker-compose.yml, so users only need to place docker-compose.yml and config.json in an empty folder and just run ``docker-compose up -d``

The docker compose file is already created on my end, but I need to test it first, also automated building and publishing of the image to the Docker registry has to be set up on your end, my fork already has automated building and publishing to the registry set up.

**Comment by rmcproductions** [comment]
I'm not into the docker meta too much, but I know about the mounts - it just doesn't seem that there is one in here. Since it seems to be [intended](https://github.com/rmcproductions/mini/pull/2#issuecomment-676196304), I will close and merge this pull request as it is in a few minutes. 
If there's anything else to know about the docker stuff, please reopen and let me know - as I said, I'm not too familiar with docker!

**Comment by rmcproductions** [comment]
Apparently, I closed this before merging.
I need a coffee,

**Review by rmcproductions — APPROVED** [review]

**Pull request merged**
